### PR TITLE
Using Restkit instead of httplib

### PR DESCRIPTION
**Pull request by daxreyes**
Hi Michael,

Here is my attempt to use restkit instead of httplib. What I basically did was replace the httplib calls with the appropriate one from restkit.

Regards,
Dax

### CODE REVIEW

**Comment by mcarter** [comment]
This seems pretty good, but there may be a problem when using this new code with channel polling options: Its possible to set a channel polling host/port to be something different from the host/port for the other types of webhooks. In this case, it looks like self.http (in Server) will already exist, and the poll will use a restkit Pool that points at the wrong server.

I may be wrong, because I don't know exactly how restkit works. What do you think?

**Comment by jordoh** [comment]
Would it be possible to use EventletPool instead of SimplePool, to provide keepalive and timeout settings? 

There's an example here: https://github.com/benoitc/restkit but I'm unclear on whether the "monkey_patch"-ing in that example would work.

**Comment by mcarter** [comment]
oh, good point jordoh. I see no reason that the monkey patch stuff wouldn't work -- though I wonder why they need to patch select... regardless, should be fine.

**Comment by jordoh** [comment]
I'm not too clear on the patching stuff myself, even after reading this: http://eventlet.net/doc/patching.html

I guess rtjp_eventlet/hookbox don't need to do the patching because they go through eventlet and don't talk to the socket lib directly?

**Comment by mcarter** [comment]
Yeah, thats exactly right... rtjp_eventlet/csp_eventlet builds directly on eventlet apis; hookbox uses httplib, but via the eventlet.green module (from eventlet.green import httplib) which means that eventlet already wraps up those apis properly.

I've used their monkey_path method before in many cases, and it tends to just work fine, so I'm not too worried.

**Comment by daxreyes** [comment]
Thanks for the comments, I have made further modifications to http_request and it now uses EventletPool instead of SimplePool

**Comment by jordoh** [comment]
Trying this out today - can you add the restkit dependency to setup.py though.

**Comment by daxreyes** [comment]
thanks jordoh, as suggested, I have recently added restkit as dependency

**Comment by jordoh** [comment]
Been running with these changes today; ~200-300 users connected at any given time with no apparent issues.

**Pull request merged**
